### ISSUE TITLE
Make use consistent: order_last and order_final

### ISSUE THREAD

**Issue by izaskr** [izaskr/chart_descriptions#51]

**Comment by emiudeh** [comment]
Can you elaborate? 
There;s currently only use of order_last.

**Comment by izaskr** [comment]
I found some instances of order_final and fixed them. I opened this issue as a reminder to fix it in other files too.

**Comment by emiudeh** [comment]
Okay. 
I think this is done. 
I wrote a script to go through all files and find instances of "order_final", but none was found. 
To verify the script works fine, I did same for "order_last" and found 59 instances in the dataset.

**Comment by izaskr** [comment]
TODO: check for "order_rest" and change into "order_last" or other suitable label.
